services:
  api:
    build: .
    command: ["python3", "-m", "src.main"]
    environment:
      PYEDIS_DATA_DIR: "/data"
      PORT: "6379"
      PYEDIS_AOF_FSYNC: "true"
    volumes:
      - data:/data
    ports:
      - "6379:6379"
  e2e:
    build: ./tests/e2e
    depends_on:
      - api
    environment:
      REDIS_URL: "redis://api:6379"
volumes:
  data:
